<<<<<<< HEAD
<<<<<<< HEAD
=======
BuildSystems = [ "setuptools",]
DowngradePython = "3.10"
>>>>>>> 01053e2ed30446105e78e3c6a6d86dd129e42b2e
=======
>>>>>>> c0969091896fdd3c5459e332658c3b9de30953a5
ManualOverrides = "__file__:python-openzwave/0.4.19/default.nix"
