<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
BuildSystems = [ "setuptools",]
DowngradePython = "3.10"
>>>>>>> 4b86a575a869296520b288fd58e6535e94de812b
=======
>>>>>>> b47eefa9fb6a201149524de49c7bdaec5b6756dd
=======
>>>>>>> f2b8b3a3c4ff2640af23e58184de2b188f6f872e
ManualOverrides = "__file__:pyimpfuzzy/0.5/default.nix"
