BuildInputs = [ "~literal:!:pkgs.blas", "~literal:!:pkgs.lapack",]
BuildSystems = [ "cmake", "numpy", "scikit-build", "setuptools", "setuptools-scm", "wheel",]
NativeBuildInputs = [ "~literal:!:pkgs.gfortran",]
