BuildSystems = [ "cython_0", "numpy", "setuptools", "setuptools-scm", "wheel",]
ManualOverrides = "__file__:algebra/1.2.1/default.nix"
TomlRequiresPatcher = [ false, false, false, false, false, false,]
