BuildInputs = [ "~literal:!:] ++ (pkgs.lib.optionals ((builtins.trace pkgs.stdenv.hostPlatform.system pkgs.stdenv.hostPlatform.system) == \"x86_64-linux\") [ pkgs.cudaPackages.cuda_cudart ]) ++ [",]
Torch = true
