BuildInputs = [ "~literal:!:pkgs.cyrus_sasl", "~literal:!:pkgs.openldap.dev", "~literal:!:pkgs.pkg-config",]
BuildSystems = [ "setuptools",]
<<<<<<< HEAD
DowngradePython = "3.11"
=======
>>>>>>> a6c26227db7f070ac9350be02b4e69b96bf608ef
