BuildSystems = [ "cython", "numpy", "setuptools", "setuptools-scm", "wheel",]
ManualOverrides = "__file__:backends/1.6.6/default.nix"
TomlRequiresPatcher = [ false, false, false, false, false, false,]
