BuildSystems = [ "setuptools",]
NativeBuildInputs = [ "~literal:!:(pkgs.boost.override {python = final.python; numpy=final.numpy; enablePython=true;})", "~literal:!:pkgs.cmake", "~literal:!:pkgs.zlib.dev",]
