BuildInputs = [ "~literal:!:pkgs.cairo",]
BuildSystems = [ "meson-python", "pycairo",]
NativeBuildInputs = [ "~literal:!:pkgs.gobject-introspection", "~literal:!:pkgs.meson", "~literal:!:pkgs.pkg-config",]
RefindBuildDirectory = true
